name: indicai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/logo.svg
   - assets/icons/local-orange.svg
   - assets/icons/arrow-right.svg
   - assets/icons/user-orange.svg
   - assets/icons/google-icon.svg

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/UbuntuSans-Regular.ttf
          weight: 400
        - asset: fonts/UbuntuSans-Medium.ttf
          weight: 500
        - asset: fonts/UbuntuSans-SemiBold.ttf
          weight: 600
        - asset: fonts/UbuntuSans-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuSans-ExtraBold.ttf
          weight: 800